# Generated by Django 3.2.6 on 2021-08-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(auto_created=True, default=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('todo_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_lists.todolist')),
            ],
        ),
    ]
